TK_1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
    path('',include('detailBarang.urls')),
    path('',include('approvalList.urls')),
    path('',include('startsell.urls')),
    path('',include('sellItem.urls')),
    path('products/', include('products.urls')),
    path('product-detail/', include('detailBarang.urls'))
]

urlpatterns += staticfiles_urlpatterns()

sellItem/urls.py
from django.urls import path
from . import views

app_name = 'sellItem'

urlpatterns= [
	path('saveItem', views.saveItem, name = 'saveItem')
	]

sellItem/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.TextField()
    prize = models.TextField()

    DRESS = 'Dress'
    T_SHIRT = 'T-Shirt'
    SKIRT = 'Skirt'
    JUMPSUIT = 'Jumpsuit'
    PANTS_LEGGINGS = 'Pants & Leggings'
    JEANS = 'Jeans'
    SWIMWEAR = 'Swimwear'
    KNITWEAR_CARDIGANS = 'Knitwear & Cardigans'
    HOODIES_SWEATSHIRTS = 'Hoodies & Sweatshirts'
    BLAZER = 'Blazer'
    JACKET_COATS = 'Jacket & Coats'
    SLEEPWEAR = 'Sleepwear'
    ACCESSORIES = 'Accessories'
    ALL = 'All'

    CATEGORY_CHOICES = [
    (DRESS, 'Dress'), (T_SHIRT, 'T-Shirt'),
    (SKIRT, 'Skirt'), (JUMPSUIT, 'Jumpsuit'),
    (PANTS_LEGGINGS, 'Pants & Leggings'),
    (JEANS, 'Jeans'), (SWIMWEAR, 'Swimwear'),
    (KNITWEAR_CARDIGANS, 'Knitwear & Cardigans'),
    (HOODIES_SWEATSHIRTS, 'Hoodies & Sweatshirts'),
    (BLAZER, 'Blazer'), (JACKET_COATS, 'Jacket & Coats'),
    (SLEEPWEAR, 'Sleepwear'), (ACCESSORIES, 'Accessories'),
    (ALL, 'All'),
    ]

    category = models.CharField(max_length = 100,
        choices=CATEGORY_CHOICES, default = ALL,
        )

    describtion = models.TextField()
    image = models.ImageField()

sellItem/views.py
from django.shortcuts import render,redirect
from .form import addItem
from .models import Category

# Create your views here.
def saveItem(request, *args, **kwargs ):
	if request.method == 'POST':
		form = addItem(request.POST)
		if form.is_valid():
			categorys = Category()
			categorys.name = form.cleaned_data['name']
			categorys.prize = form.cleaned_data['prize']
			categorys.category = form.cleaned_data['category']
			categorys.describtion= form.cleaned_data['describtion']
			categorys.image = form.cleaned_data['image']
			categorys.save()
		return redirect('/saveItem')
	else:
		form = addItem()
	categorys = Category.objects.all()
	context ={
		'form' : form,
		'category' : categorys
	}
	return render(request, 'sellitem.html', context )

sellItem/templates/sellitem.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href="{% static 'css/font-awsome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Asap&display=swap" rel="stylesheet">

 
    <title>AppaRental</title>
</head>

<body>
    <div class="top-footer">
        <a href="#">
            <button type="button" class="logo">AppaRental.</button>
        </a>
    </div>

    <div class="container-fluid" id="wrapper-top">
        <a class="tulisan-back" href="#">
            <i class="fa fa-arrow-circle-left"></i>
            <p>Back to Products Page</p>
        </a>

        <div class="container-fluid" id="wrapper">
                
                <div class="bawah">
                    <h5>Sell Your Item</h5>
                    <hr>

                    <div class="container-fluid" id="wrapper_content">
                       <form method = "POST" action="{%url 'sellItem:saveItem' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class='bottom'>
                            <a href="#">
                                <button type="button" class="btn" style="margin-left: 2.5rem; margin-top: 3rem;">Sell Item</button>
                            </a>
                        </div>
                    </div>

                </div>
        </div>
    </div>

    <div class="bottom-footer">
       <p>© 2019 All rights served</p>
    </div>
    <!-- Optional JavaScript -->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>

</body>

</html>